//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePozoriste.WinUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ePozoriste.WinUI.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobro nam došli.
        /// </summary>
        internal static string DobroDosli {
            get {
                return ResourceManager.GetString("DobroDosli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka mora sadržavati najmanje 8 karaktera..
        /// </summary>
        internal static string DuzinaLozinke {
            get {
                return ResourceManager.GetString("DuzinaLozinke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do greške..
        /// </summary>
        internal static string Greska {
            get {
                return ResourceManager.GetString("Greska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacija.
        /// </summary>
        internal static string Informacija {
            get {
                return ResourceManager.GetString("Informacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne mozete obrisati jer se koristi!.
        /// </summary>
        internal static string NeMozeteObrisati {
            get {
                return ResourceManager.GetString("NeMozeteObrisati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos ove vrijednosti je obavezan..
        /// </summary>
        internal static string ObaveznaVrijednost {
            get {
                return ResourceManager.GetString("ObaveznaVrijednost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uneseni podaci nisu validni..
        /// </summary>
        internal static string PodaciNisuValidni {
            get {
                return ResourceManager.GetString("PodaciNisuValidni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci uspješno dodati u bazu..
        /// </summary>
        internal static string PodaciUspjesnoDodati {
            get {
                return ResourceManager.GetString("PodaciUspjesnoDodati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci uspješno modifikovani..
        /// </summary>
        internal static string PodaciUspjesnoModifikovani {
            get {
                return ResourceManager.GetString("PodaciUspjesnoModifikovani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podatak je već dodat..
        /// </summary>
        internal static string PodatakVecPostoji {
            get {
                return ResourceManager.GetString("PodatakVecPostoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unijeli ste pogresno korisičko ime ili lozinku..
        /// </summary>
        internal static string PogresnaLozinkaIliMail {
            get {
                return ResourceManager.GetString("PogresnaLozinkaIliMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozorenje.
        /// </summary>
        internal static string Upozorenje {
            get {
                return ResourceManager.GetString("Upozorenje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj telefona treba biti u formatu 000-000-000 ili 000-000-0000..
        /// </summary>
        internal static string ValidacijaBrTelefona {
            get {
                return ResourceManager.GetString("ValidacijaBrTelefona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email treba biti u formatu &quot;naziv@emailadresa.domena&quot;..
        /// </summary>
        internal static string ValidacijaEmaila {
            get {
                return ResourceManager.GetString("ValidacijaEmaila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sala je zauzeta u tom terminu!.
        /// </summary>
        internal static string ZauzetaSala {
            get {
                return ResourceManager.GetString("ZauzetaSala", resourceCulture);
            }
        }
    }
}
